application: whoisok
version: 1
api_version: 1
runtime: python

handlers:
- url: /css
  static_dir: templates/css
- url: /images
  static_dir: templates/images
- url: /scripts
  static_dir: templates/scripts
- url: .*
  script: main.py
